# Generated by Django 4.2.9 on 2024-01-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashgame',
            name='name',
        ),
        migrations.RemoveField(
            model_name='poker',
            name='name',
        ),
    ]
